define: &exclude_folders "^(examples/|tests/)"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "examples/"
      - id: check-added-large-files
        exclude: "^(examples/|docs/source/_static/|src/datasets/)"
        args: ["--maxkb=1100"]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
        exclude: *exclude_folders
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        exclude: *exclude_folders
        types: [ python ]
        exclude: 'tests/'
        # Replace the version below with the latest pyright version
        additional_dependencies: [ 'pyright@1.1.268' ]
