[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.pyright]
strict = ['**']
exclude = ['src/utils/pandas.py', 'src/graph/p_graph.py', '**/__init__.py']
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
strictParameterNoneValue = true
reportUnusedImport = "none"
