[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.pyright]
useLibraryCodeForTypes = false
#strict = ['**']
typeCheckingMode = 'basic'
stubPath = './typings'
exclude = [
#    'src/utils/pandas.py',
#    'src/graph/p_graph.py',
    '**/__init__.py',
    './typings',
    './examples',
    './.tox'
]
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
strictParameterNoneValue = true
reportUntypedFunctionDecorator = "error"
reportUntypedClassDecorator = "error"
reportUntypedBaseClass = "error"
#reportUnusedVariable = "error"
reportUnusedClass = "error"
reportUnnecessaryCast = "error"
reportUnnecessaryComparison = "error"
reportUnnecessaryContains = "error"
reportUnnecessaryIsInstance = "error"
reportImportCycles = "error"
reportDuplicateImport = "error"

[tool.mypy]
exclude = ['^examples/00_pickle_params_model\.py$']

[[tool.mypy.overrides]]
module = "examples"
ignore_errors = true
